---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    hostname: molecule
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare/playbook.yml
    converge: converge/playbook.yml
    verify: verify/playbook.yml
  inventory:
    host_vars:
      instance:
        ssh_port: 12345
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  name: default
  create_sequence:
    - create
  check_sequence:
    - create
    - converge
    - check
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - create
    - prepare
    - converge # install the role
    - verify
    - idempotence
    - verify
    - destroy
